### PR TITLE
AUTO

### PR DESCRIPTION
**Pull request by sumukhballal**

### CODE REVIEW

**Comment by AbhiniveshP** [comment]
Nice work Sumukh !!!
The space complexity that you mentioned is correct and you can optimize the space by performing backtracking. Once backtracking questions are covered, you can retry this question again if you are not able to figure out to optimize space for now.

**Comment by AbhiniveshP** [comment]
Nice work Sumukh !!!
The space complexity that you mentioned is correct and you can optimize the space by performing backtracking. Once backtracking questions are covered, you can retry this question again if you are not able to figure out to optimize space for now.

**Comment by sumukhballal** [comment]
Thanks will try

**Comment by sumukhballal** [comment]
Done added backtracking section

**Pull request closed without merging**
